### ISSUE TITLE
removing a migration file model

### ISSUE THREAD

**Issue by skylarktechteam** [elygreenberg/NobleRails#12]
<img width="301" alt="screen shot 2015-11-21 at 8 27 28 pm" src="https://cloud.githubusercontent.com/assets/14908580/11321477/046abfca-908f-11e5-8a50-af081c63fa5a.png">

Hi Ely
 I'd like to remove a migration. I rolled it back and replaced it with a better named and simpler model.

Can I just delete 20151121034834_create_jjobs.rb file

I have nt run the rake db:migrate again and I'd like to NOT have this jjobs model run and make tables.

John

**Comment by skylarktechteam** [comment]
Ely
If I also remove and delete the Model file jjob.rb 

does that get rid of that wrong model jjob completly or anything else needs to be done- 

John

**Comment by elygreenberg** [comment]
Hi John, 

The best way to remove a migration and /or model is: 

rake db:rollback to undo the migration. 
Then rails d model "name of model". This will delete both the model file and the first migration file that was auto generated when the model was created. 
Be sure to also delete any associations with the deleted model since this will create errors later on. 
If you delete the model first without rolling back the migration you'll get some nasty errors since the migration will have been deleted so rails can't roll anything back. 

Ely

**Comment by pxlcty** [comment]
Hi class,
I found a helpful and simple "One to many relationship" video tutorial.
It's in Rails 3, so you need to add the permit method in the Controller for
the create/edit actions. Otherwise I had no problem running it on my end.

https://www.youtube.com/watch?v=1rlz081lrnU
